//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCut.Shared.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByKepiSevkiyat.Shared.Resources.Localization.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string Account_No {
            get {
                return ResourceManager.GetString("Account No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add All.
        /// </summary>
        internal static string Add_All {
            get {
                return ResourceManager.GetString("Add All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected.
        /// </summary>
        internal static string Add_Selected {
            get {
                return ResourceManager.GetString("Add Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding customer order..
        /// </summary>
        internal static string An_error_occurred_while_adding_customer_order_ {
            get {
                return ResourceManager.GetString("An error occurred while adding customer order.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding shipment order..
        /// </summary>
        internal static string An_error_occurred_while_adding_shipment_order_ {
            get {
                return ResourceManager.GetString("An error occurred while adding shipment order.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the product..
        /// </summary>
        internal static string An_error_occurred_while_adding_the_product_ {
            get {
                return ResourceManager.GetString("An error occurred while adding the product.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the price..
        /// </summary>
        internal static string An_error_occurred_while_changing_the_price_ {
            get {
                return ResourceManager.GetString("An error occurred while changing the price.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting..
        /// </summary>
        internal static string An_error_occurred_while_deleting_ {
            get {
                return ResourceManager.GetString("An error occurred while deleting.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting loading order..
        /// </summary>
        internal static string An_error_occurred_while_deleting_loading_order_ {
            get {
                return ResourceManager.GetString("An error occurred while deleting loading order.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting shipment order..
        /// </summary>
        internal static string An_error_occurred_while_deleting_shipment_order_ {
            get {
                return ResourceManager.GetString("An error occurred while deleting shipment order.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching data from server..
        /// </summary>
        internal static string An_error_occurred_while_fetching_data_from_server_ {
            get {
                return ResourceManager.GetString("An error occurred while fetching data from server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching data from the system..
        /// </summary>
        internal static string An_error_occurred_while_fetching_data_from_the_system_ {
            get {
                return ResourceManager.GetString("An error occurred while fetching data from the system.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching the loading quantity..
        /// </summary>
        internal static string An_error_occurred_while_fetching_the_loading_quantity_ {
            get {
                return ResourceManager.GetString("An error occurred while fetching the loading quantity.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while filtering..
        /// </summary>
        internal static string An_error_occurred_while_filtering_ {
            get {
                return ResourceManager.GetString("An error occurred while filtering.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while listing details..
        /// </summary>
        internal static string An_error_occurred_while_listing_details_ {
            get {
                return ResourceManager.GetString("An error occurred while listing details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while listing loading orders..
        /// </summary>
        internal static string An_error_occurred_while_listing_loading_orders_ {
            get {
                return ResourceManager.GetString("An error occurred while listing loading orders.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while listing shipment orders..
        /// </summary>
        internal static string An_error_occurred_while_listing_shipment_orders_ {
            get {
                return ResourceManager.GetString("An error occurred while listing shipment orders.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the page..
        /// </summary>
        internal static string An_error_occurred_while_loading_the_page_ {
            get {
                return ResourceManager.GetString("An error occurred while loading the page.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while printing label..
        /// </summary>
        internal static string An_error_occurred_while_printing_label_ {
            get {
                return ResourceManager.GetString("An error occurred while printing label.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while recording shipment orders..
        /// </summary>
        internal static string An_error_occurred_while_recording_shipment_orders_ {
            get {
                return ResourceManager.GetString("An error occurred while recording shipment orders.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing shipment details..
        /// </summary>
        internal static string An_error_occurred_while_removing_shipment_details_ {
            get {
                return ResourceManager.GetString("An error occurred while removing shipment details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing the product..
        /// </summary>
        internal static string An_error_occurred_while_removing_the_product_ {
            get {
                return ResourceManager.GetString("An error occurred while removing the product.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the shipment order..
        /// </summary>
        internal static string An_error_occurred_while_saving_the_shipment_order_ {
            get {
                return ResourceManager.GetString("An error occurred while saving the shipment order.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while scanning barcode..
        /// </summary>
        internal static string An_error_occurred_while_scanning_barcode_ {
            get {
                return ResourceManager.GetString("An error occurred while scanning barcode.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating package quantities..
        /// </summary>
        internal static string An_error_occurred_while_updating_package_quantities_ {
            get {
                return ResourceManager.GetString("An error occurred while updating package quantities.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has occurred..
        /// </summary>
        internal static string An_unhandled_error_has_occurred_ {
            get {
                return ResourceManager.GetString("An unhandled error has occurred.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Details.
        /// </summary>
        internal static string Bank_Details {
            get {
                return ResourceManager.GetString("Bank Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Number.
        /// </summary>
        internal static string Barcode_Number {
            get {
                return ResourceManager.GetString("Barcode Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary.
        /// </summary>
        internal static string Beneficiary {
            get {
                return ResourceManager.GetString("Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code.
        /// </summary>
        internal static string Branch_Code {
            get {
                return ResourceManager.GetString("Branch Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Actions.
        /// </summary>
        internal static string Bulk_Actions {
            get {
                return ResourceManager.GetString("Bulk Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Company_Name {
            get {
                return ResourceManager.GetString("Company Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container No.
        /// </summary>
        internal static string Container_No {
            get {
                return ResourceManager.GetString("Container No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        internal static string Continue_ {
            get {
                return ResourceManager.GetString("Continue?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to couldn&apos;t be scanned..
        /// </summary>
        internal static string could_not_be_scanned_ {
            get {
                return ResourceManager.GetString("could not be scanned.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find sales order belonging to barcode..
        /// </summary>
        internal static string Could_not_find_sales_order_belonging_to_barcode_ {
            get {
                return ResourceManager.GetString("Could not find sales order belonging to barcode.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read barcode..
        /// </summary>
        internal static string Could_not_read_barcode_ {
            get {
                return ResourceManager.GetString("Could not read barcode.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Loading Order.
        /// </summary>
        internal static string Create_Loading_Order {
            get {
                return ResourceManager.GetString("Create Loading Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shipment Order.
        /// </summary>
        internal static string Create_Shipment_Order {
            get {
                return ResourceManager.GetString("Create Shipment Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string Customer_Name {
            get {
                return ResourceManager.GetString("Customer Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order No.
        /// </summary>
        internal static string Customer_Order_Number {
            get {
                return ResourceManager.GetString("Customer Order Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order Qty.
        /// </summary>
        internal static string Customer_Order_Quantity {
            get {
                return ResourceManager.GetString("Customer Order Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Term.
        /// </summary>
        internal static string Delivery_Term {
            get {
                return ResourceManager.GetString("Delivery Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        internal static string Deselect_All {
            get {
                return ResourceManager.GetString("Deselect All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm deletion?.
        /// </summary>
        internal static string Do_you_confirm_deletion_ {
            get {
                return ResourceManager.GetString("Do you confirm deletion?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm the record process?.
        /// </summary>
        internal static string Do_you_confirm_the_record_process_ {
            get {
                return ResourceManager.GetString("Do you confirm the record process?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Filter.
        /// </summary>
        internal static string Enter_Filter {
            get {
                return ResourceManager.GetString("Enter Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: Production State.
        /// </summary>
        internal static string Filter__Production_State {
            get {
                return ResourceManager.GetString("Filter: Production State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        internal static string IBAN {
            get {
                return ResourceManager.GetString("IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        internal static string Invoice_No {
            get {
                return ResourceManager.GetString("Invoice No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Produced?.
        /// </summary>
        internal static string Is_Produced_ {
            get {
                return ResourceManager.GetString("Is Produced?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Scanned.
        /// </summary>
        internal static string Is_Scanned {
            get {
                return ResourceManager.GetString("Is Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Info.
        /// </summary>
        internal static string Label_Info {
            get {
                return ResourceManager.GetString("Label Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Quantity.
        /// </summary>
        internal static string Loaded_Quantity {
            get {
                return ResourceManager.GetString("Loaded Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading exists..
        /// </summary>
        internal static string Loading_exists_ {
            get {
                return ResourceManager.GetString("Loading exists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading List.
        /// </summary>
        internal static string Loading_List {
            get {
                return ResourceManager.GetString("Loading List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading order deleted..
        /// </summary>
        internal static string Loading_order_deleted_ {
            get {
                return ResourceManager.GetString("Loading order deleted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Order Details.
        /// </summary>
        internal static string Loading_Order_Details {
            get {
                return ResourceManager.GetString("Loading Order Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Order Line.
        /// </summary>
        internal static string Loading_Order_Line {
            get {
                return ResourceManager.GetString("Loading Order Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Order No.
        /// </summary>
        internal static string Loading_Order_Number {
            get {
                return ResourceManager.GetString("Loading Order Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Report.
        /// </summary>
        internal static string Loading_Report {
            get {
                return ResourceManager.GetString("Loading Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic Application.
        /// </summary>
        internal static string Logistic_Application {
            get {
                return ResourceManager.GetString("Logistic Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one identical barcode..
        /// </summary>
        internal static string More_than_one_identical_barcode_ {
            get {
                return ResourceManager.GetString("More than one identical barcode.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Filter.
        /// </summary>
        internal static string No_Filter {
            get {
                return ResourceManager.GetString("No Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shipment Order found in the system..
        /// </summary>
        internal static string No_Shipment_Order_found_in_the_system_ {
            get {
                return ResourceManager.GetString("No Shipment Order found in the system.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shipment orders found ready for loading..
        /// </summary>
        internal static string No_shipment_orders_found_ready_for_loading_ {
            get {
                return ResourceManager.GetString("No shipment orders found ready for loading.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ready.
        /// </summary>
        internal static string Not_Ready {
            get {
                return ResourceManager.GetString("Not Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Package.
        /// </summary>
        internal static string Number_of_Package {
            get {
                return ResourceManager.GetString("Number of Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Line No.
        /// </summary>
        internal static string Order_Line_Number {
            get {
                return ResourceManager.GetString("Order Line Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Quantity.
        /// </summary>
        internal static string Order_Quantity {
            get {
                return ResourceManager.GetString("Order Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package amount must greater than zero..
        /// </summary>
        internal static string Package_amount_must_greater_than_zero_ {
            get {
                return ResourceManager.GetString("Package amount must greater than zero.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package amount to be updated couldn&apos;t be found..
        /// </summary>
        internal static string Package_amount_to_be_updated_couldn_t_be_found_ {
            get {
                return ResourceManager.GetString("Package amount to be updated couldn\'t be found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package info couldn&apos;t be found..
        /// </summary>
        internal static string package_info_couldn_t_be_found_ {
            get {
                return ResourceManager.GetString("package info couldn\'t be found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Label.
        /// </summary>
        internal static string Package_Label {
            get {
                return ResourceManager.GetString("Package Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package quantities are updated..
        /// </summary>
        internal static string Package_quantities_are_updated_ {
            get {
                return ResourceManager.GetString("Package quantities are updated.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Qty.
        /// </summary>
        internal static string Package_Quantity {
            get {
                return ResourceManager.GetString("Package Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Sequence.
        /// </summary>
        internal static string Package_Sequence {
            get {
                return ResourceManager.GetString("Package Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing List.
        /// </summary>
        internal static string Packing_List {
            get {
                return ResourceManager.GetString("Packing List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term.
        /// </summary>
        internal static string Payment_Term {
            get {
                return ResourceManager.GetString("Payment Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one product..
        /// </summary>
        internal static string Please_add_at_least_one_product_ {
            get {
                return ResourceManager.GetString("Please add at least one product.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid amount..
        /// </summary>
        internal static string Please_enter_a_valid_amount_ {
            get {
                return ResourceManager.GetString("Please enter a valid amount.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO No.
        /// </summary>
        internal static string PO_No {
            get {
                return ResourceManager.GetString("PO No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price didn&apos;t change. Please try again..
        /// </summary>
        internal static string Price_didn_t_change__Please_try_again_ {
            get {
                return ResourceManager.GetString("Price didn\'t change. Please try again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Label.
        /// </summary>
        internal static string Print_Label {
            get {
                return ResourceManager.GetString("Print Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produced.
        /// </summary>
        internal static string Produced {
            get {
                return ResourceManager.GetString("Produced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string Product_Code {
            get {
                return ResourceManager.GetString("Product Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string Product_Name {
            get {
                return ResourceManager.GetString("Product Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found in the list..
        /// </summary>
        internal static string Product_not_found_in_the_list_ {
            get {
                return ResourceManager.GetString("Product not found in the list.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sequence.
        /// </summary>
        internal static string Product_Sequence {
            get {
                return ResourceManager.GetString("Product Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity to Send.
        /// </summary>
        internal static string Quantity_to_Send {
            get {
                return ResourceManager.GetString("Quantity to Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string Report_Type {
            get {
                return ResourceManager.GetString("Report Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative.
        /// </summary>
        internal static string Representative {
            get {
                return ResourceManager.GetString("Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order added....
        /// </summary>
        internal static string Sales_order_added___ {
            get {
                return ResourceManager.GetString("Sales order added...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order already added..
        /// </summary>
        internal static string Sales_order_already_added_ {
            get {
                return ResourceManager.GetString("Sales order already added.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order loaded couldn&apos;t be found..
        /// </summary>
        internal static string Sales_order_loaded_couldn_t_be_found_ {
            get {
                return ResourceManager.GetString("Sales order loaded couldn\'t be found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order not shipped belonging to this barcode number couldn&apos;t be found..
        /// </summary>
        internal static string Sales_order_not_shipped_belonging_to_this_barcode_number_couldn_t_be_found_ {
            get {
                return ResourceManager.GetString("Sales order not shipped belonging to this barcode number couldn\'t be found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Report.
        /// </summary>
        internal static string Sales_Report {
            get {
                return ResourceManager.GetString("Sales Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned Quantity.
        /// </summary>
        internal static string Scanned_Quantity {
            get {
                return ResourceManager.GetString("Scanned Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Deleted..
        /// </summary>
        internal static string Shipment_Deleted_ {
            get {
                return ResourceManager.GetString("Shipment Deleted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment List.
        /// </summary>
        internal static string Shipment_List {
            get {
                return ResourceManager.GetString("Shipment List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment order could not be saved. Please try again..
        /// </summary>
        internal static string Shipment_order_could_not_be_saved__Please_try_again_ {
            get {
                return ResourceManager.GetString("Shipment order could not be saved. Please try again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment order details could not be found..
        /// </summary>
        internal static string Shipment_order_details_could_not_be_found_ {
            get {
                return ResourceManager.GetString("Shipment order details could not be found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment order details couldn&apos;t be found..
        /// </summary>
        internal static string Shipment_order_details_couldn_t_be_found_ {
            get {
                return ResourceManager.GetString("Shipment order details couldn\'t be found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Order Line.
        /// </summary>
        internal static string Shipment_Order_Line {
            get {
                return ResourceManager.GetString("Shipment Order Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Order List.
        /// </summary>
        internal static string Shipment_Order_List {
            get {
                return ResourceManager.GetString("Shipment Order List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Order No.
        /// </summary>
        internal static string Shipment_Order_Number {
            get {
                return ResourceManager.GetString("Shipment Order Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Order Quantity.
        /// </summary>
        internal static string Shipment_Order_Quantity {
            get {
                return ResourceManager.GetString("Shipment Order Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment order quantity can not be greater than sales order quantity..
        /// </summary>
        internal static string Shipment_order_quantity_can_not_be_greater_than_sales_order_quantity_ {
            get {
                return ResourceManager.GetString("Shipment order quantity can not be greater than sales order quantity.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment order saved successfully..
        /// </summary>
        internal static string Shipment_order_saved_successfully_ {
            get {
                return ResourceManager.GetString("Shipment order saved successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment orders couldn&apos;t be found....
        /// </summary>
        internal static string Shipment_orders_couldn_t_be_found___ {
            get {
                return ResourceManager.GetString("Shipment orders couldn\'t be found...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment orders recorded successfully..
        /// </summary>
        internal static string Shipment_orders_recorded_successfully_ {
            get {
                return ResourceManager.GetString("Shipment orders recorded successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Ready Quantity.
        /// </summary>
        internal static string Shipment_Ready_Quantity {
            get {
                return ResourceManager.GetString("Shipment Ready Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Report.
        /// </summary>
        internal static string Shipment_Report {
            get {
                return ResourceManager.GetString("Shipment Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Quantity.
        /// </summary>
        internal static string Shipped_Quantity {
            get {
                return ResourceManager.GetString("Shipped Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Shipping Order.
        /// </summary>
        internal static string Show_Shipping_Order {
            get {
                return ResourceManager.GetString("Show Shipping Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT.
        /// </summary>
        internal static string SWIFT {
            get {
                return ResourceManager.GetString("SWIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same shipment order cannot be added more than once..
        /// </summary>
        internal static string The_same_shipment_order_cannot_be_added_more_than_once_ {
            get {
                return ResourceManager.GetString("The same shipment order cannot be added more than once.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Package Qty.
        /// </summary>
        internal static string Total_Package_Quantity {
            get {
                return ResourceManager.GetString("Total Package Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Licence No.
        /// </summary>
        internal static string Trade_Licence_No {
            get {
                return ResourceManager.GetString("Trade Licence No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Selected.
        /// </summary>
        internal static string Update_Selected {
            get {
                return ResourceManager.GetString("Update Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD Account.
        /// </summary>
        internal static string USD_Account {
            get {
                return ResourceManager.GetString("USD Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel &amp; Voyage No.
        /// </summary>
        internal static string Vessel___Voyage_No {
            get {
                return ResourceManager.GetString("Vessel & Voyage No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong barcode format..
        /// </summary>
        internal static string Wrong_barcode_format_ {
            get {
                return ResourceManager.GetString("Wrong barcode format.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
